-- ═══════════════════════════════════════════════════════════════════════════
-- Las pruebas de esta migración se MUDARON a la 018.
--
-- La 018 le cambió la firma a `ops.create_quote_request`: la patente pasó a
-- ser opcional (`quote_requests.plate` es nullable en el backend) y se sumó
-- `p_vehicle_text`. Agregar un parámetro no REEMPLAZA una función —crea una
-- sobrecarga—, así que la 018 hace DROP + CREATE, y esta suite quedó llamando
-- a una firma que ya no existe. Además su caso 19 ("patente vacía rechazada")
-- afirma justo lo que la 018 vino a cambiar.
--
-- Mismo movimiento que 008 → 009 y 013 → 016: las mismas aserciones en dos
-- suites obligan a mantener las dos, y la que se olvida falla por razones que
-- no tienen que ver con el código. Todo lo que esta suite probaba y sigue
-- valiendo (canal, teléfono y descripción obligatorios, `raw_submission`
-- marcado como carga manual, el log con `before` NULL, actor inexistente) está
-- en la 018, casos 10–35.
--
--   → migrations/018_ops_editar_pedido.test.sql
-- ═══════════════════════════════════════════════════════════════════════════
