-- ═══════════════════════════════════════════════════════════════════════════
-- Las pruebas de esta migración se MUDARON a la 016.
--
-- La 016 (`.claude/plans/pedidos-ficha-2026-09-25.md`) reestructuró
-- `ops.quote_request_rubro` de "un rubro por pedido" a "varios rubros por
-- pedido": DROPEÓ esta tabla y la recreó con otra PK, y DROPEÓ
-- `ops.set_quote_request_rubro` (singular) en favor de
-- `ops.set_quote_request_rubros` (plural, conjunto completo). Mismo motivo
-- que dejó a `008_ops_partner_perfil_y_links.test.sql` sin las pruebas de
-- `set_partner_profile` cuando la 009 le agregó un parámetro: agregar un
-- parámetro (o, acá, cambiar la forma entera) NO reemplaza una función
-- existente — la vieja y la nueva son sobrecargas distintas, y esta suite
-- corriendo después de la 016 fallaría contra una función que ya no existe.
--
-- No queda nada de esta suite que siga siendo válido: la tabla que probaba
-- ya no tiene esa forma, y la función que probaba ya no existe.
--
--   → migrations/016_ops_varios_rubros_y_nota_de_cierre.test.sql
-- ═══════════════════════════════════════════════════════════════════════════
